import { z } from 'zod';

export const StoreFormSchema = z.object({
  cmp_code: z.string().min(1, 'Company Code is required'),
  cmp_name: z.string().min(1, 'Company Name is required'),
  ou_code: z.number().int(),
  ou_name: z.string().min(1, 'Operating Unit Name is required'),
  sg_code: z.string().min(1, 'Store Group Code is required'),
  sg_name: z.string().min(1, 'Store Group Name is required'),
  store_code: z.string().min(1, 'Store Code is required'),
  store_name: z.string().min(1, 'Store Name is required'),
  add1: z.string().min(1, 'Address Line 1 is required'),
  add2: z.string().optional(),
  country_code: z.string().min(1, 'Country Code is required'),
  state_code: z.string().min(1, 'State Code is required'),
  city_code: z.number().int(),
  pin: z.number().int(),
  phone: z.string().optional(),
  email: z.string().optional(),
  contact_person: z.string().optional(),
  contact_phone: z.string().optional(),
  contact_mail: z.string().optional(),
  blocked: z.string().optional(),
  vat_regn_no: z.string().optional(),
  tan_no: z.string().optional(),
  gstin: z.string().optional(),
  arn_no: z.string().optional(),
  tcan_no: z.string().optional(),
  pan_no: z.string().optional(),
  restaurant: z.string().optional(),
  currency_code: z.string().optional(),
  inventory_check: z.string().optional(),
  pos_no_series: z.string().optional(),
  pine_lab_integration: z.string().optional(),
  paytm_integration: z.string().optional(),
  network_integration: z.string().optional(),
  ezetap_integration: z.string().optional(),
});

export type StoreFormValues = z.infer<typeof StoreFormSchema>;
